'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type Clothing = { id:string; name:string; category:string; color:string; size:string|null; brand:string|null; image_url:string|null; created_at:string };
const categories = ['Camisetas','Camisas','Calças','Shorts','Bermudas','Jaquetas','Casacos','Tênis','Sapatos','Acessórios','Outros'];

export default function Home() {
  const [items,setItems]=useState<Clothing[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Clothing|null>(null); const [search,setSearch]=useState(''); const [filter,setFilter]=useState('Todos');
  const load=async()=>{ if(!supabase){setLoading(false);return;} const {data,error}=await supabase.from('clothing').select('*').order('created_at',{ascending:false}); if(error)setError(error.message); else setItems(data||[]); setLoading(false); };
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>(filter==='Todos'||i.category===filter)&&(`${i.name} ${i.brand||''} ${i.color}`.toLowerCase().includes(search.toLowerCase()))),[items,search,filter]);
  const remove=async(id:string)=>{if(!supabase||!confirm('Excluir esta peça?'))return;const {error}=await supabase.from('clothing').delete().eq('id',id);if(error)setError(error.message);else setItems(x=>x.filter(i=>i.id!==id));};
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const payload={name:String(f.get('name')),category:String(f.get('category')),color:String(f.get('color')),size:String(f.get('size')||''),brand:String(f.get('brand')||''),image_url:String(f.get('image_url')||'')}; const result=editing?await supabase.from('clothing').update(payload).eq('id',editing.id).select().single():await supabase.from('clothing').insert(payload).select().single(); if(result.error){setError(result.error.message);return;} setOpen(false);setEditing(null);load();};
  const openEdit=(item:Clothing)=>{setEditing(item);setOpen(true)};
  return <div className="app"><header className="header"><div className="brand"><div className="brand-mark">⌁</div>Meu Closet</div><button className="primary" onClick={()=>{setEditing(null);setOpen(true)}}>+ Adicionar peça</button></header>
    <main className="container"><section className="hero"><div><p className="eyebrow">Seu guarda-roupa, organizado</p><h1>Vista o que você já tem.</h1><p>Cadastre suas peças, encontre tudo rapidamente e tenha uma visão simples do seu closet.</p></div></section>
      <section className="stats"><div className="stat"><span>Total de peças</span><strong>{items.length}</strong></div><div className="stat"><span>Categorias</span><strong>{new Set(items.map(i=>i.category)).size}</strong></div><div className="stat"><span>Peça mais recente</span><strong>{items[0]?.name||'—'}</strong></div></section>
      <div className="toolbar"><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, marca ou cor..." /></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
      {error&&<div className="empty" style={{marginBottom:18}}>{error}<br/><small>Configure as variáveis do Supabase e execute o SQL em <b>supabase/schema.sql</b>.</small></div>}
      {loading?<div className="empty">Carregando seu closet...</div>:filtered.length===0?<div className="empty"><div style={{fontSize:40}}>◌</div><h3>{items.length?'Nenhuma peça encontrada':'Seu closet começa aqui'}</h3><p>{items.length?'Tente outro termo ou categoria.':'Adicione sua primeira peça para começar a organizar.'}</p></div>:<div className="grid">{filtered.map(item=><article className="card" key={item.id}><div className="photo">{item.image_url?<img src={item.image_url} alt={item.name}/>:<div className="hanger">♧</div>}</div><div className="card-body"><div className="card-top"><h3>{item.name}</h3><span className="tag">{item.category}</span></div><div className="meta">{item.color}{item.brand?` · ${item.brand}`:''}{item.size?` · Tam. ${item.size}`:''}</div><div className="actions"><button className="ghost" onClick={()=>openEdit(item)}>Editar</button><button className="ghost danger" onClick={()=>remove(item.id)}>Excluir</button></div></div></article>)}</div>}
    </main>{open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setOpen(false);setEditing(null)}}}><div className="modal"><div className="modal-header"><div><p className="eyebrow">{editing?'Atualizar':'Nova peça'}</p><h2>{editing?'Editar roupa':'Adicionar ao closet'}</h2></div><button className="close" onClick={()=>{setOpen(false);setEditing(null)}}>×</button></div><form className="form" onSubmit={save}><div className="field full"><label>Nome da peça *</label><input name="name" required defaultValue={editing?.name||''} placeholder="Ex.: Camiseta oversized"/></div><div className="field"><label>Categoria *</label><select name="category" required defaultValue={editing?.category||'Camisetas'}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Cor *</label><input name="color" required defaultValue={editing?.color||''} placeholder="Ex.: Verde oliva"/></div><div className="field"><label>Marca</label><input name="brand" defaultValue={editing?.brand||''} placeholder="Ex.: Nike"/></div><div className="field"><label>Tamanho</label><input name="size" defaultValue={editing?.size||''} placeholder="Ex.: M, 42, 10"/></div><div className="field full"><label>URL da foto</label><input name="image_url" type="url" defaultValue={editing?.image_url||''} placeholder="https://..."/></div><div className="form-footer"><button type="button" className="ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">{editing?'Salvar alterações':'Adicionar peça'}</button></div></form></div></div>}</div>
}
